### ISSUE TITLE
Add DER encoded X.509 certificate 

### ISSUE THREAD

**Issue by r3dlight** [bojand/infer#29]
Hi,

May I ask you to support DER encoded X.509 certificate please ?
Hex signature : 30 82

Thanks !

**Comment by bojand** [comment]
Hello this should be addressed in [0.3.3](https://github.com/bojand/infer/releases/tag/v0.3.3). [crates.io](https://crates.io/crates/infer).

**Comment by r3dlight** [comment]
Thanks !
