### ISSUE TITLE
Feature request: Add support for obj, dll, msi

### ISSUE THREAD

**Issue by r3dlight** [bojand/infer#33]
Hi,

Could you add support for:

Microsoft Installer | .msi | D0 CF 11 E0 A1 B1 1A E1
Object Code File | .obj | 4C 01
Dynamic Library | .dll | 4D 5A [MZ]

Thanks !

**Comment by bojand** [comment]
Please review #36.

**Comment by r3dlight** [comment]
That seems perfect, thanks !

**Comment by bojand** [comment]
Published in version 0.3.6.
