### ISSUE TITLE
add get_classname(), which returns a string representation of the file class

### ISSUE THREAD

**Issue by ppenguin** [bojand/infer#41]
One use case of this lib is to want to get the identified file class (`App`, `Video`, ..., `Other`).
This functionality is also missing in the referred to `go` lib, but would be really practical, since if files just need to be categorized, the full mime type is too verbose/exact.

**Comment by bojand** [comment]
Hello this can be achieved using [`Type::matcher_type()`](https://docs.rs/infer/0.5.0/infer/struct.Type.html#method.matcher_type):
```rust
let info = infer::Infer::new();
let buf = [0xFF, 0xD8, 0xFF, 0xAA];
let kind = info.get(&buf).expect("file type is known");
assert_eq!(kind.matcher_type(), infer::MatcherType::Image);
```
