### ISSUE TITLE
Test data not included in crate

### ISSUE THREAD

**Issue by janbaudisch** [bojand/infer#47]
The `testdata` directory is explicitly excluded from the published crate. This means that tests fail when using crates.io as a source (for packaging on Linux distros for example). Is there a reason for this? I can see that the crate would get bigger this way, but right now it is not really having everything needed.

**Comment by janbaudisch** [comment]
Same goes for the `tests` directory.

**Comment by bojand** [comment]
These directories should be included in [0.7.0](https://github.com/bojand/infer/releases/tag/v0.7.0).
