### ISSUE TITLE
Doctest failed in fedora packaging

### ISSUE THREAD

**Issue by remilauzier** [bojand/infer#54]
The failed test seem to be because of missing file.
https://download.copr.fedorainfracloud.org/results/remilauzier/infer/fedora-rawhide-x86_64/03495386-rust-infer/builder-live.log.gz

failures:

---- src/lib.rs - get_from_path (line 453) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'file read successfully: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/lib.rs:5:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by bojand** [comment]
I think this might be due to `testdata` missing from the published crate, (see #47), which has been included in [0.7.0](https://github.com/bojand/infer/releases/tag/v0.7.0). If it persists feel free to reopen the issue.
