### ISSUE TITLE
Does not correctly detect plain text

### ISSUE THREAD

**Issue by WillNilges** [bojand/infer#85]
I expect this is because a file produced by `echo "hello world!" >> /tmp/hello_world.txt` doesn't _have_ a MIME type, but is there any way to handle this?

**Comment by bojand** [comment]
This library is not intended to work with text-based files with arbitrary content that do not have deterministic magic number bytes header within them. My recommendation is to [add a customer matcher](https://docs.rs/infer/latest/infer/#adds-a-custom-file-type-matcher) for your specific use case if possible.
