### ISSUE TITLE
What were the semver breaking changes `0.13` -> `0.14`?

### ISSUE THREAD

**Issue by alexheretic** [bojand/infer#90]
Hello, thanks for your work on this crate. I noticed you published a new version and came to see what the break was and how/if I needed to adapt to that change downstream.

I can't see any breaking changes in https://github.com/bojand/infer/releases/tag/v0.14.0 though. How come this was published as a breaking semver bump?

If a change has no breaking changes it can make life a bit easier downstream (ie for me) by publishing as a non-breaking semver bump.

**Comment by alexheretic** [comment]
Ah I assume you just don't follow semver. That makes it harder to continuing using this crate. But if you never intended to follow semver sorry for the noise.

**Comment by bojand** [comment]
Hello, my intent is to follow semver, however strictly speaking, when major version is zero (ie 0.y.z), technically anything may change at any time. That being said I am careful about changes in this crate. There were no breaking changes as you stated. Normally I use patch version update for only minor superficial fixes or changes. When something new gets added (like zstd skippable frames in 0.14) I do increment the minor version to signify "something new". 
Should there be API or breaking changes it will be clearly noted in the release notes. 
I do have plans for some changes in the future when I get some more time that may require API changes over time, but even those I will try to be iterative and careful with.
Sorry for the confusion. Hope this helps.
